#
#
#
#

#
#title: Page24
#title_separator : "-"
#subtitle:
#name :
#description :
#url:
#baseurl:
#BATH_PATH: https://takagotch.github.io/page24/
#repository: 
#teaser :
#logo :
#masthead_title :
#breadcrumbs :
#words_per_minute : 
#comments:
#
#

title: dbyll
disqus: dbyll-ghost # disqus short name
author:  
  name: yourname  
  email: youremail  
  github: asd123  
  twitter: asd123  
  pinterest: asd123  
  linkedin: asd123  
  resume: asd123  
  bio: Your stylish,  minimalist theme!  
  email_md5: md5ofemail  

#
#

title: TKVTV
disqus: tkvtv-ghost
description: Your stylish, minimalist theme!

name: "tkgcci"

author:
  name : takagotch
  # social
  github: takagotch
  twitter: takagotch
  email: takagotch
  email_md5: 
  bio: allowed yall requests till my account limit goes on tails!
  email_md5: takagotch
  
  
BATH_PATH:  https://takagotch.github.io/page24/  


category_path: 
# type:
  path: /categories/

tags:
  path: /tags/
  
  
sidebar_background_image: # project-block  
  
time: 2020  
  
